# @package _global_

defaults:
  - /indexing/data/default@data_loader
  - /indexing/text_units/default@text_unit_extractor
  - /indexing/graph_generation/generator@graph_generator  
  - /indexing/graph_clustering/default@community_detector
  - /indexing/table_generation/entities@entities_table_generator  
  - /indexing/table_generation/relationships@relationships_table_generator  
  - /indexing/table_generation/communities@communities_table_generator  
  - /indexing/table_generation/text_units@text_units_table_generator  
  - /indexing/table_generation/reports@communities_report_table_generator  
  - /indexing/embedding_generation/graph@entities_table_generator.graph_embedding_generator  
  


_target_: langchain_graphrag.indexing.indexer.Indexer
output_dir: ${paths.artifacts_dir}
  